export const projects = [
    {
        id: 1,
        name: 'Progressive Budget',
        href: '#',
        price: 'This pwa app is designed to allow a user to budget their finances by adding or deducting funds on/offline.',
        imageSrc: './progress.png',
        imageAlt: 'pwa app screenshot',
    },
    {
        id: 2,
        name: 'Workout Tracker',
        href: '#',
        price: 'This Full-stack project is designed to allow a user to post and keep track of previous workouts.',
        imageSrc: './workout.png',
        imageAlt: 'workout tracker screenshot',
    },
    {
        id: 3,
        name: 'Cats-n-Dogs',
        href: '#',
        price: 'A fullstack group project focused on building an application that would allow users to find/post lost or stray animals in their neighborhood or area to help find them a home',
        imageSrc: 'https://user-images.githubusercontent.com/53482411/131909367-02c7a2dc-90b9-4e0c-afca-5f6ed5a28d1f.png',
        imageAlt: 'Cats-n-Dogs app screenshot',
    },
    {
        id: 4,
        name: 'Work Day Scheduler',
        href: '#',
        price: 'A simple calendar application that allows a user to save events for each hour of the day',
        imageSrc: './scheduler.png',
        imageAlt: 'Work day scheduler screenshot',
    },
    {
        id: 5,
        name: 'Password Generator',
        href: '#',
        price: 'An application designed to generate a random password based off of user input',
        imageSrc: './password.png',
        imageAlt: 'Password generator screenshot',
    },
    {
        id: 6,
        name: 'Employee Tracker',
        href: '#',
        price: 'This project is a CLI content management system for managing a company\'s employees using node, inquirer, and MySQL',
        imageSrc: './employee.gif',
        imageAlt: 'Gif for employee tracker',
    },
]
    // More Projects..